// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqNJlGVLqUULW5Fb0fGGOIvGdvPt3v_zQ',
    appId: '1:212889377357:web:06e5f108904de2b6c05a04',
    messagingSenderId: '212889377357',
    projectId: 'recipeapp-cff45',
    authDomain: 'recipeapp-cff45.firebaseapp.com',
    storageBucket: 'recipeapp-cff45.appspot.com',
    measurementId: 'G-JWT9HFL3CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdO4jpL6lq1yGJc00AZhBCP_9SGi_Psgw',
    appId: '1:212889377357:android:7e8e7ceb2d5e63d2c05a04',
    messagingSenderId: '212889377357',
    projectId: 'recipeapp-cff45',
    storageBucket: 'recipeapp-cff45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLegP5ZpPw_wFEfR1CyeNavWbcsbHzL8',
    appId: '1:212889377357:ios:a076cab8b80a39d9c05a04',
    messagingSenderId: '212889377357',
    projectId: 'recipeapp-cff45',
    storageBucket: 'recipeapp-cff45.appspot.com',
    iosBundleId: 'com.example.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLegP5ZpPw_wFEfR1CyeNavWbcsbHzL8',
    appId: '1:212889377357:ios:ac182c73deda3412c05a04',
    messagingSenderId: '212889377357',
    projectId: 'recipeapp-cff45',
    storageBucket: 'recipeapp-cff45.appspot.com',
    iosBundleId: 'com.example.recipeapp.RunnerTests',
  );
}
